### ISSUE TITLE
Implementation of gradual pruning procedure

### ISSUE THREAD

**Issue by Godofnothing** [IST-DASLab/M-FAC#1]
Hi! 
Thanks for a great job, your results are pretty impressive and the code can be easily adapted to Torchvision models. 

So far, as I understand, there is an implementation of one-shot pruning and one-shot pruning with recomputes. 

Do you plan to add gradual pruning to the repository in the future? 

So far, the pruner is able to prune weights but doesn't freeze them for the optimization procedure (i.e doesn't block gradients on pruned weights).

**Comment by efrantar** [comment]
Hi!

Sorry for the late reply.

We just pushed code for performing gradual pruning. Note that the interface of `main_prun.py` changed quite a bit, please see the new example in the README.

**Comment by Godofnothing** [comment]
Great, thanks!
